apiVersion: v1
kind: Service
metadata:
  name: hello-python-service
spec:
  selector:
    name: pod-hello-python
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 5000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: hello-python
  name: hello-python
spec:
  replicas: 3
  selector:
    matchLabels:
      name: pod-hello-python
  template:
    metadata:
      labels:
        name: pod-hello-python
      name: hello-python
    spec:
      containers:
      - name: hello-python
        image: hello-python:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000

